// src/config/icons.js
import { library } from "@fortawesome/fontawesome-svg-core";
import {
  faHome,
  faUser,
  faBriefcase,
  faEnvelope,
  faBirthdayCake,
  faMapMarkerAlt,
  faPhone,
  faCopy,
  faCode,
  faLanguage,
  faDatabase,
  faStar,
} from "@fortawesome/free-solid-svg-icons";
import {
  faGithub,
  faFacebook,
  faTwitter,
  faLinkedin,
  faReact,
  faHtml5,
  faJs,
  faCss3,
  faNodeJs,
} from "@fortawesome/free-brands-svg-icons";
library.add(
  faHome,
  faUser,
  faBriefcase,
  faEnvelope,
  faBirthdayCake,
  faMapMarkerAlt,
  faPhone,
  faGithub,
  faFacebook,
  faLinkedin,
  faTwitter,
  faCopy,
  faLanguage,
  faReact,
  faHtml5,
  faJs,
  faCss3,
  faNodeJs,
  faCode,
  faDatabase,
  faStar
);
